#+AUTHOR: Simon Stoltze
#+EMAIL: sstoltze@gmail.com
* Overview
This repository is for playing around with various tools and frameworks for topological data analysis.

The different folders will (hopefully) be written in a literate programming style using org-mode and org-babel. A guide to getting started with literate programming in R can be found [[https://orgmode.org/worg/org-contrib/babel/how-to-use-Org-Babel-for-R.html][here]]. The tutorial [[http://howardism.org/Technical/Emacs/literate-programming-tutorial.html][here]] can also be useful, in particular for setting up tangling.

* Tangle

** Header
I have the following header to work with org-babel.
#+BEGIN_EXAMPLE
#+BABEL: :session *R* :cache yes :results output graphics :exports both :tangle yes
#+END_EXAMPLE
This appears to do nothing. Instead, use [[Multiple files]].

** Multiple files
To get tangle to work, and output multiple files from the same org document, I found property-drawers to be the easiest solution. In a given section, add a property drawer with
#+BEGIN_EXAMPLE
:PROPERTIES:
:header-args: :tangle tutorial.R :cache yes
:END:
#+END_EXAMPLE
This can be done with C-c C-x p, entering header-args as the property and the rest of the line as the value.

* Issues

** R libraries
To get R to install libraries on linux, I needed to change /usr/local/lib/R/site-library to writable:
#+BEGIN_SRC sh
sudo chmod a+w /usr/local/lib/R/site-library/
#+END_SRC
Alternatively, you could use a local library but this seems like the easiest way to do it.

** Sessions
There seems to be some issue with org-babel and sessions. The following piece of code works fine:
#+BEGIN_EXAMPLE
#+BEGIN_SRC R
1 + 1
#+END_SRC
#+END_EXAMPLE
But this code makes emacs hang after confirming the working directory:
#+BEGIN_EXAMPLE
#+BEGIN_SRC R :session *R*
1 + 1
#+END_SRC
#+END_EXAMPLE

For now, I'll stick to tangling and working with the R file directly, but this adds an extra step and is a bit annoying.

The only info I could find was the following StackExchange post: [[https://emacs.stackexchange.com/questions/19735/emacs-freezes-with-any-org-babel-snippet-using-session]]
